version: '3.8'
services:
  app:
    build: .
    image: foundernest-challenge-oscargilbalaguer
    volumes:
      - ./results:/results
    entrypoint: ["/bin/bash"]
    environment:
      DATABASE_URI: "sqlite:////results/database.db"
      DATABASE_PATH: "/results/database.db"
      API_TOKEN: "BGjvhpFqkIFoBCvD0wwP" # TODO: Put API token here, between the quotes
